// claims (P4): the mathematical claims ledger, every clause of the mission §7 row measured.
//   1. the 30 true claims pass through the in-process claim() API (+ the tolerance claims pass only with tol)
//   2. the 15 false claims (subtle sign errors) each raise AssertionError naming the expr
//   3. an unparseable claim raises ValueError — not a pass, not an AssertionError
//   4. num() shows the computed value: num(Matrix([[3,1],[1,2]]).det()) == "5"
//   5. --independent: every ledger entry re-derived in a FRESH python process from its text alone agrees
//      with the in-scene verdict (one process per claim, sequential — never two pythons at once)
//   6. a failing claim BLOCKS: a planted false scene fails checkMathFilm loudly with the expr; removed, all ok
//   7. coverage() arithmetic on a 10-sentence fixture (9 mathematical, 8 linked -> 88.9%)
// Python runs through runCapped (D-007), one process at a time.
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { CAPS, TIMEOUTS, runCapped } from '../../lib/capped.mjs';
import { pythonFor } from '../../doctor.mjs';
import { ROOT } from '../../lib/serve.mjs';
import { FILMS } from '../../lib/film.mjs';

const KEY = 'verify-m-claims';
const MANIM = join(ROOT, 'engine', 'manim');
const PLANTED = 'Matrix([[1, 3], [2, 1]]).det() == 5';

// 10 sentences: s07 has no digit and no equality word (not mathematical); s05 is mathematical but
// no claim says it (unlinked) -> 9 mathematical, 8 linked, 88.9%.
const SENTENCES = [
  { id: 's01', text: 'This matrix has determinant 5.' },
  { id: 's02', text: 'The area scales by the determinant.' },
  { id: 's03', text: 'Three times two minus one equals five.' },
  { id: 's04', text: 'The unit square becomes a parallelogram.' },
  { id: 's05', text: 'Swapping the columns gives minus five.' },
  { id: 's06', text: 'The derivative of x cubed is three x squared.' },
  { id: 's07', text: 'Watch the grid closely.' },
  { id: 's08', text: 'One third plus one sixth makes a half: 1/2.' },
  { id: 's09', text: 'Every limit here are computed, not typed.' },
  { id: 's10', text: 'The identity matrix multiplies nothing away.' },
];
const SAYS = ['s01', 's02', 's03', 's04', 's06', 's08', 's09', 's10'];

const DRIVER = `# generated by engine/verify/math/claims.mjs — the in-process claims battery
import json, os, sys, warnings
warnings.filterwarnings("ignore")
from studio_manim.claims import claim, coverage, merge_ledgers, _LEDGER
from studio_manim.typeset import num
from sympy import Matrix
job = json.load(sys.stdin)
cases = job["cases"]
out = {"true_pass": [], "true_fail": [], "false_raised": [], "false_bad": [], "tol": [], "error": []}
for e in cases["true"]:
    try:
        r = claim(e, about="battery true", says="true")
        (out["true_pass"] if r is True else out["true_fail"]).append([e, repr(r)])
    except BaseException as ex:
        out["true_fail"].append([e, type(ex).__name__ + ": " + str(ex)[:160]])
for e in cases["false"]:
    try:
        r = claim(e, about="battery false", says="false")
        out["false_bad"].append([e, "no raise, returned " + repr(r)])
    except AssertionError as ex:
        msg = str(ex)
        (out["false_raised"] if repr(e) in msg or e in msg else out["false_bad"]).append([e, msg[:200]])
    except BaseException as ex:
        out["false_bad"].append([e, type(ex).__name__ + ": " + str(ex)[:160]])
for c in cases["tolerance"]:
    row = {"expr": c["expr"], "tol": c["tol"]}
    try:
        row["with_tol"] = claim(c["expr"], tol=c["tol"], about="battery tolerance", says="tol")
    except BaseException as ex:
        row["with_tol"] = type(ex).__name__
    from studio_manim.claims import evaluate
    row["exact"] = evaluate(c["expr"])[0]  # exact by default: the decimal alone is NOT equal
    out["tol"].append(row)
n_ledger = len(_LEDGER)
for e in cases["error"]:
    try:
        claim(e, about="battery unparseable")
        out["error"].append([e, "PASSED"])
    except ValueError as ex:
        out["error"].append([e, "ValueError", str(ex)[:120]])
    except AssertionError as ex:
        out["error"].append([e, "AssertionError"])
    except BaseException as ex:
        out["error"].append([e, type(ex).__name__])
out["num"] = num(Matrix([[3, 1], [1, 2]]).det())
out["num_frac"] = num(Matrix([[1, 3], [2, 1]]).det())
out["ledger_n"] = n_ledger
cov = coverage(job["sentences"], [{"expr": "1 == 1", "says": s} for s in job["says"]])
out["coverage"] = cov
# merge_ledgers: the same scene ledger in two formats dedupes by (expr, says)
rec = job["records"]
os.makedirs(os.path.join(rec, "16:9"), exist_ok=True); os.makedirs(os.path.join(rec, "9:16"), exist_ok=True)
led = json.load(open(job["claims_file"]))
json.dump(led, open(os.path.join(rec, "16:9", "s01-claims.json"), "w"))
json.dump(led, open(os.path.join(rec, "9:16", "s01-claims.json"), "w"))
out["merged_n"] = len(merge_ledgers(rec))
print("RESULT " + json.dumps(out))
`;

const py = () => pythonFor('manim');
const env = (extra = {}) => ({ PYTHONPATH: MANIM, STUDIO_FORMAT: '16:9', ...extra });

export default async (ctx = {}) => {
  const t0 = Date.now();
  const work = join(ctx.cache || join(tmpdir(), 'verify-math'), 'claims');
  rmSync(work, { recursive: true, force: true }); mkdirSync(work, { recursive: true });
  const cases = JSON.parse(readFileSync(join(MANIM, 'test', 'claims-cases.json'), 'utf8'));
  const facts = [], bad = [];
  if (cases.true.length !== 30 || cases.false.length !== 15) bad.push(`battery is ${cases.true.length} true / ${cases.false.length} false (want 30/15)`);

  // -- clauses 1-4, 7 (+ merge_ledgers): one capped process through the real claim() API -----
  const claimsFile = join(work, 'battery-claims.json');
  writeFileSync(join(work, 'film_state.json'), JSON.stringify({ claims_file: claimsFile, scene: { id: 'battery' } }));
  writeFileSync(join(work, 'driver.py'), DRIVER);
  const r = await runCapped(py(), [join(work, 'driver.py')], {
    cwd: MANIM, memoryMb: CAPS.check, timeoutS: TIMEOUTS.check, label: 'claims battery',
    env: env({ STUDIO_FILM_STATE: join(work, 'film_state.json') }),
    input: JSON.stringify({ cases, sentences: SENTENCES, says: SAYS, records: join(work, 'records'), claims_file: claimsFile }),
  });
  if (r.killed) return { pass: false, measured: `claims battery killed (${r.reason})` };
  const line = (r.out || '').split('\n').find((l) => l.startsWith('RESULT '));
  if (!line) return { pass: false, measured: `battery produced no result: ${(r.err || r.out).slice(-400)}` };
  const o = JSON.parse(line.slice(7));

  // 1
  if (o.true_pass.length === 30 && !o.true_fail.length) facts.push('30/30 true pass');
  else bad.push(`true claims: ${o.true_pass.length}/30 pass; failing: ${o.true_fail.map((f) => `${f[0]} -> ${f[1]}`).join(' | ')}`);
  const tolOk = o.tol.every((t) => t.with_tol === true && t.exact === false);
  if (tolOk) facts.push(`${o.tol.length}/${o.tol.length} tolerance claims pass with tol, fail exact`);
  else bad.push(`tolerance: ${JSON.stringify(o.tol)}`);
  // 2
  if (o.false_raised.length === 15 && !o.false_bad.length) facts.push('15/15 false raise AssertionError naming the expr');
  else bad.push(`false claims: ${o.false_raised.length}/15 raised; bad: ${o.false_bad.map((f) => `${f[0]} -> ${f[1]}`).join(' | ')}`);
  // 3
  const errOk = o.error.length === cases.error.length && o.error.every((e) => e[1] === 'ValueError');
  if (errOk) facts.push(`${o.error.length}/${cases.error.length} unparseable -> ValueError`);
  else bad.push(`unparseable: ${JSON.stringify(o.error)}`);
  // 4
  if (o.num === '5' && o.num_frac === '-5') facts.push(`num(det)="${o.num}"`);
  else bad.push(`num(det) = ${JSON.stringify(o.num)} / ${JSON.stringify(o.num_frac)} (want "5" / "-5")`);
  // 7
  const cov = o.coverage;
  if (cov.mathematical.length === 9 && cov.linked.length === 8 && cov.pct === 88.9 && cov.unlinked.join() === 's05')
    facts.push(`coverage ${cov.linked.length}/${cov.mathematical.length} = ${cov.pct}%`);
  else bad.push(`coverage: ${JSON.stringify(cov)} (want 8/9 = 88.9%, unlinked s05)`);
  // the ledger claim() wrote via state.claims_file, and its film-level merge
  let ledger = [];
  try { ledger = JSON.parse(readFileSync(claimsFile, 'utf8')); } catch (e) { bad.push(`claim() wrote no ledger: ${e.message}`); }
  const scored = ledger.filter((c) => c.ok !== null);
  const want = cases.true.length + cases.false.length + cases.tolerance.length;
  if (scored.length !== want || ledger.some((c) => c.scene !== 'battery' || (c.ok !== null && typeof c.value !== 'string')))
    bad.push(`ledger: ${scored.length} scored entries (want ${want}), scene/value fields ${ledger.every((c) => c.scene === 'battery') ? 'ok' : 'missing'}`);
  if (o.merged_n !== new Set(ledger.map((c) => `${c.expr}\u0000${c.says}`)).size) bad.push(`merge_ledgers: ${o.merged_n} entries from 2 identical format ledgers of ${ledger.length}`);
  else facts.push(`merge_ledgers dedupes 2x${ledger.length} -> ${o.merged_n}`);

  // -- clause 5: --independent, one fresh process per claim, from its text alone ---------------
  const indep = { agree: 0, disagree: [] };
  for (const [i, c] of scored.entries()) {
    const f = join(work, `one-${i}.json`);
    writeFileSync(f, JSON.stringify([{ expr: c.expr, ok: c.ok, ...(c.tol != null ? { tol: c.tol } : {}) }]));
    const ri = await runCapped(py(), ['-W', 'ignore', '-m', 'studio_manim.claims', '--independent', f], {
      cwd: MANIM, memoryMb: CAPS.check, timeoutS: 120, label: `claims independent ${i}`, env: env(),
    });
    let row = null;
    try { row = JSON.parse((ri.out || '').trim().split('\n').at(-1))[0]; } catch { /* reported below */ }
    if (ri.code === 0 && row?.agrees === true && row.ok === c.ok) indep.agree++;
    else indep.disagree.push(`${c.expr} (ledger ok=${c.ok}, independent ${row ? `ok=${row.ok}` : (ri.err || '').slice(-120)}, exit ${ri.code})`);
  }
  // the CLI's verdict means something: a tampered ledger (one flipped flag) exits 1 with agrees:false
  const tamper = join(work, 'tampered.json');
  writeFileSync(tamper, JSON.stringify([{ expr: cases.false[0], ok: true }, { expr: cases.true[0], ok: true }]));
  const rt = await runCapped(py(), ['-W', 'ignore', '-m', 'studio_manim.claims', '--independent', tamper], {
    cwd: MANIM, memoryMb: CAPS.check, timeoutS: 120, label: 'claims independent tampered', env: env(),
  });
  let trows = null; try { trows = JSON.parse(rt.out.trim().split('\n').at(-1)); } catch { /* below */ }
  const tamperOk = rt.code === 1 && trows?.[0]?.agrees === false && trows?.[1]?.agrees === true;
  if (indep.agree === scored.length && !indep.disagree.length && tamperOk)
    facts.push(`--independent ${indep.agree}/${scored.length} agree (fresh process each; tampered ledger exits 1)`);
  else bad.push(`--independent: ${indep.agree}/${scored.length} agree; ${indep.disagree.slice(0, 4).join(' | ')}${tamperOk ? '' : `; tampered ledger exit ${rt.code} ${rt.out.slice(-160)}`}`);

  // -- clause 6: a failing claim blocks the scene, loudly; removed, the film checks clean --------
  const { createMathFilm, checkMathFilm } = await import('../../math-cli.mjs');
  rmSync(join(FILMS, KEY), { recursive: true, force: true });
  try {
    const dir = createMathFilm(KEY, { title: 'claims fixture' });
    const planted = join(dir, 'scenes', 's99_false.py');
    writeFileSync(planted, `from studio_manim import StudioScene, claim


class Scene(StudioScene):
    """s99_false — a planted false claim (the claims check): the scene must not pass."""

    scene_id = "s99_false"

    def construct(self):
        claim(${JSON.stringify(PLANTED)}, about="planted false")
        self.wait(0.5)
`);
    const rows1 = await checkMathFilm(KEY);
    const s99 = rows1.find((x) => x.scene === 's99_false');
    const others1 = rows1.filter((x) => x.scene !== 's99_false');
    const loud = s99 && s99.ok === false && (s99.error || '').includes(PLANTED) && /CLAIM FAILED/.test(s99.error || '');
    if (!loud) bad.push(`planted false claim not blocked loudly: ${JSON.stringify(s99)}`);
    if (!others1.length || others1.some((x) => !x.ok)) bad.push(`with the planted scene, other scenes: ${JSON.stringify(others1)}`);
    rmSync(planted);
    const rows2 = await checkMathFilm(KEY);
    const clean = rows2.length === others1.length && rows2.every((x) => x.ok && x.claims > 0);
    if (!clean) bad.push(`after removing the planted scene: ${JSON.stringify(rows2)}`);
    if (loud && clean) facts.push(`planted false scene blocked ("${(s99.error.split('\n').find((l) => l.includes('CLAIM FAILED')) || '').trim().slice(0, 90)}"), removed -> ${rows2.length}/${rows2.length} scenes ok (${rows2.reduce((a, x) => a + x.claims, 0)} claims)`);
  } finally {
    rmSync(join(FILMS, KEY), { recursive: true, force: true });
  }

  rmSync(work, { recursive: true, force: true });
  const secs = Math.round((Date.now() - t0) / 1000);
  return { pass: bad.length === 0, measured: `${(bad.length ? bad : facts).join('; ')} [${secs}s]` };
};
