// layout-lint (P3): the lint is MEASURED on fixtures, not asserted. Four legs:
//  1. 12 seeded violations (engine/manim/test/lint-fixtures, generated by its make.mjs): each is
//     reported with the right rule, level, object ids, source line and time (+/- 1 frame), and nothing else
//     — including the overflow that exists only in 9:16 (its 16:9 twin must be clean);
//  2. 0 false positives on 6 clean scenes, two of them legitimate overlaps (axis ticks, brace + label)
//     whose CONTROL run (allow_pairs removed) must fire — the allowance is what makes them clean;
//  3. the solver places 8 crowded labels around an octagon: zero overlaps (checked here, in JS, not by
//     the solver), every center within max_distance of its anchor, identical output on every run, and
//     an infeasible case raises naming the label;
//  4. the real leg: films/verify-m-lint, scene s01_hook rendered at draft 16:9 through renderMathFilm,
//     its REAL records linted with the film's design.json -> 0 fail-level violations.
// Python runs as few capped processes as possible (one batch + the two CLIs), one at a time.
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { CAPS, TIMEOUTS, MemPool } from '../../lib/capped.mjs';
import { pythonFor } from '../../doctor.mjs';
import { ROOT } from '../../lib/serve.mjs';
import { FILMS, readJson } from '../../lib/film.mjs';

const KEY = 'verify-m-lint';
const FIX = join(ROOT, 'engine', 'manim', 'test', 'lint-fixtures');
const MANIM = join(ROOT, 'engine', 'manim');

const BATCH = `
import json, sys, warnings
warnings.filterwarnings("ignore")
from pathlib import Path
from studio_manim.lint import lint_dir, DEFAULT_ALLOW
from studio_manim.solver import place_labels, PlacementError
job = json.load(sys.stdin)
fix = Path(job["fixtures"])
design = json.loads((fix / "design.json").read_text())
out = {"cases": {}, "controls": {}}
for name in job["cases"]:
    case = json.loads((fix / name / "case.json").read_text())
    allow = tuple(tuple(p) for p in case["allow_pairs"]) if case["allow_pairs"] is not None else DEFAULT_ALLOW
    out["cases"][name] = {v["fmt"]: lint_dir(fix / name / "records" / v["fmt"].replace(":", "x"), design, v["fmt"], allow)
                          for v in case["variants"]}
    if case.get("control"):
        out["controls"][name] = {v["fmt"]: lint_dir(fix / name / "records" / v["fmt"].replace(":", "x"), design, v["fmt"], ())
                                 for v in case["variants"]}
sc = json.loads((fix / "solver-octagon.json").read_text())
runs = [place_labels(sc["anchors"], sc["sizes"], sc["obstacles"], sc["max_distance"], sc["step"]) for _ in range(2)]
out["solver"] = [[list(p) for p in r] for r in runs]
bad = json.loads((fix / "solver-infeasible.json").read_text())
try:
    place_labels(bad["anchors"], bad["sizes"], bad["obstacles"], bad["max_distance"], bad["step"])
    out["infeasible"] = {"raised": False}
except PlacementError as e:
    out["infeasible"] = {"raised": True, "label": e.index, "tries": e.tries, "msg": str(e)}
print("RESULT " + json.dumps(out))
`;

const sortIds = (a) => [...a].sort();
const sameIds = (a, b) => JSON.stringify(sortIds(a)) === JSON.stringify(sortIds(b));
const hits = (a, b) => Math.min(a[0] + a[2], b[0] + b[2]) - Math.max(a[0], b[0]) > 0 &&
  Math.min(a[1] + a[3], b[1] + b[3]) - Math.max(a[1], b[1]) > 0;

function parseJson(r, tag) {
  const text = (r.out || '').trim();
  if (tag) {
    const line = text.split('\n').find((l) => l.startsWith(tag));
    return line ? JSON.parse(line.slice(tag.length)) : null;
  }
  try { return JSON.parse(text); } catch { return null; }
}

export default async (ctx = {}) => {
  const pool = new MemPool();
  const py = pythonFor('manim');
  const env = { PYTHONPATH: MANIM, STUDIO_FORMAT: '16:9' };
  const pyRun = (args, input, label) => pool.run({ cmd: py, args, cwd: MANIM, input, memoryMb: CAPS.check,
    timeoutS: TIMEOUTS.check * 2, label, env });
  const bad = [], facts = [];
  const cases = readdirSync(FIX).filter((d) => existsSync(join(FIX, d, 'case.json'))).sort();
  const spec = Object.fromEntries(cases.map((c) => [c, readJson(join(FIX, c, 'case.json'))]));
  const seeded = cases.filter((c) => spec[c].kind === 'seeded'), clean = cases.filter((c) => spec[c].kind === 'clean');
  if (seeded.length !== 12 || clean.length !== 6) bad.push(`fixtures: ${seeded.length} seeded / ${clean.length} clean (want 12 / 6) — run lint-fixtures/make.mjs`);

  // ---- legs 1-3: one batch process ----
  const cache = ctx.cache || join(tmpdir(), 'verify-m-lint'); mkdirSync(cache, { recursive: true });
  const prog = join(cache, 'layout-lint-batch.py'); writeFileSync(prog, BATCH);
  const r = await pyRun([prog], JSON.stringify({ fixtures: FIX, cases }), 'layout-lint batch');
  if (r.killed) return { pass: false, measured: `lint batch killed (${r.reason})` };
  const res = parseJson(r, 'RESULT ');
  if (!res) return { pass: false, measured: `lint batch produced no result:\n${((r.out || '') + (r.err || '')).slice(-600)}` };

  // 1. seeded: every expected violation present (rule, level, ids, t +/- 1 frame, source line, aspect),
  //    and NOTHING unexpected
  let seededOk = 0, variantsChecked = 0, tErrMax = 0;
  for (const c of seeded) {
    let caseOk = true;
    for (const v of spec[c].variants) {
      variantsChecked++;
      const got = res.cases[c][v.fmt] || [];
      const frame = 1 / v.fps;
      const used = new Set();
      for (const e of v.expect) {
        const i = got.findIndex((g, k) => !used.has(k) && g.rule === e.rule && sameIds(g.ids, e.ids));
        if (i < 0) { caseOk = false; bad.push(`${c} ${v.fmt}: ${e.rule} on ${e.ids} NOT reported (got ${JSON.stringify(got.map((g) => [g.rule, g.ids, g.t]))})`); continue; }
        used.add(i);
        const g = got[i];
        const dt = Math.abs(g.t - e.t); tErrMax = Math.max(tErrMax, dt);
        if (g.level !== e.level) { caseOk = false; bad.push(`${c} ${v.fmt}: ${e.rule} level ${g.level}, want ${e.level}`); }
        if (dt > frame + 1e-9) { caseOk = false; bad.push(`${c} ${v.fmt}: t ${g.t}, want ${e.t} +/- ${frame.toFixed(4)}`); }
        if (g.source_line !== e.source_line) { caseOk = false; bad.push(`${c} ${v.fmt}: source ${g.source_line}, want ${e.source_line}`); }
        if (e.aspect && !g.detail.includes(e.aspect)) { caseOk = false; bad.push(`${c} ${v.fmt}: detail "${g.detail}" lacks ${e.aspect}`); }
      }
      const extra = got.filter((_, k) => !used.has(k));
      if (extra.length) { caseOk = false; bad.push(`${c} ${v.fmt}: unexpected ${JSON.stringify(extra.map((g) => [g.rule, g.level, g.ids, g.t]))}`); }
    }
    if (caseOk) seededOk++;
  }
  // the one-format overflow: explicitly 16:9 silent, 9:16 loud
  const ov = res.cases['overflow-one-format'] || {};
  const ovFacts = `overflow 16:9=${(ov['16:9'] || []).length} / 9:16=${(ov['9:16'] || []).length}`;
  const dens = (res.cases['density-6'] || {})['16:9']?.[0];
  facts.push(`seeded ${seededOk}/${seeded.length} cases exact (${variantsChecked} format variants; max |dt| ${tErrMax.toFixed(4)} s; ${ovFacts}; density level=${dens?.level})`);

  // 2. clean: zero violations of ANY level; the allowance controls must fire
  let fp = 0, controlsOk = 0, controls = 0;
  for (const c of clean) {
    for (const v of spec[c].variants) {
      const got = res.cases[c][v.fmt] || [];
      if (got.length) { fp += got.length; bad.push(`${c} ${v.fmt}: false positives ${JSON.stringify(got.map((g) => [g.rule, g.level, g.ids, g.detail]))}`); }
      if (spec[c].control) {
        controls++;
        const ctl = (res.controls[c] || {})[v.fmt] || [];
        if (ctl.some((g) => g.rule === spec[c].control)) controlsOk++;
        else bad.push(`${c} ${v.fmt}: control (no allow_pairs) did not fire ${spec[c].control} — the fixture proves nothing`);
      }
    }
  }
  facts.push(`clean ${clean.length} scenes, ${fp} false positives (allowance controls fire ${controlsOk}/${controls})`);

  // 3. solver (checked here, independently of the solver's own test)
  const sc = readJson(join(FIX, 'solver-octagon.json'));
  const [p1, p2] = res.solver;
  const boxes = p1.map(([x, y], i) => [x - sc.sizes[i][0] / 2, y - sc.sizes[i][1] / 2, sc.sizes[i][0], sc.sizes[i][1]]);
  let overlaps = 0, maxD = 0;
  for (let i = 0; i < boxes.length; i++) {
    for (let j = i + 1; j < boxes.length; j++) if (hits(boxes[i], boxes[j])) overlaps++;
    for (const o of sc.obstacles) if (hits(boxes[i], o)) overlaps++;
    maxD = Math.max(maxD, Math.hypot(p1[i][0] - sc.anchors[i][0], p1[i][1] - sc.anchors[i][1]));
  }
  const solverCli = parseJson(await pyRun(['-m', 'studio_manim.solver'], readFileSync(join(FIX, 'solver-octagon.json'), 'utf8'), 'solver cli'));
  const det = JSON.stringify(p1) === JSON.stringify(p2) && solverCli?.ok && JSON.stringify(solverCli.positions) === JSON.stringify(p1);
  if (p1.length !== 8) bad.push(`solver placed ${p1.length}/8`);
  if (overlaps) bad.push(`solver: ${overlaps} overlaps`);
  if (maxD > sc.max_distance + 1e-9) bad.push(`solver: a label ${maxD.toFixed(3)} from its anchor > ${sc.max_distance}`);
  if (!det) bad.push(`solver not deterministic (batch x2 + CLI): ${JSON.stringify([p1, p2, solverCli])}`);
  if (!res.infeasible?.raised || res.infeasible.label !== 0) bad.push(`solver: infeasible case did not raise naming label 0: ${JSON.stringify(res.infeasible)}`);
  facts.push(`solver ${p1.length} labels, ${overlaps} overlaps, max anchor distance ${maxD.toFixed(3)} <= ${sc.max_distance}, deterministic=${!!det} (2 runs + CLI), infeasible raises (label ${res.infeasible?.label}, ${res.infeasible?.tries} tries)`);

  // 4. the real leg: one draft render of s01_hook at 16:9, lint its records via the CLI
  rmSync(join(FILMS, KEY), { recursive: true, force: true });
  try {
    const { createMathFilm } = await import('../../math-cli.mjs');
    const { renderMathFilm } = await import('../../math.mjs');
    createMathFilm(KEY, { title: 'layout-lint fixture' });
    const t0 = Date.now();
    await renderMathFilm(KEY, { quality: 'draft', fmt: '16:9', scene: 's01_hook' });
    const secs = ((Date.now() - t0) / 1000).toFixed(1);
    const recDir = join(FILMS, KEY, 'records', '16x9');
    const layout = readJson(join(recDir, 's01_hook-layout.json'), []);
    const objs = layout.flatMap((f) => f.objects || []);
    const texts = objs.filter((o) => o.text);
    const lr = await pyRun(['-m', 'studio_manim.lint', recDir, join(FILMS, KEY, 'design.json'), '16:9'], '', 'lint cli (real)');
    const vs = parseJson(lr);
    if (!Array.isArray(vs)) bad.push(`real leg: lint CLI gave no JSON: ${((lr.out || '') + (lr.err || '')).slice(-400)}`);
    else {
      const fails = vs.filter((x) => x.level === 'fail'), warns = vs.filter((x) => x.level === 'warn');
      if (!objs.length) bad.push('real leg: the recorder wrote 0 objects — the lint would pass vacuously');
      if (fails.length) bad.push(`real leg: ${fails.length} FAIL violations: ${JSON.stringify(fails.map((x) => [x.rule, x.t, x.ids, x.detail]))}`);
      const kinds = [...new Set(objs.map((o) => o.kind))].sort().join('/');
      facts.push(`real s01_hook draft 16:9 (${secs} s): ${layout.length} frames, ${objs.length} objects (${kinds}), ` +
        `${texts.length} text (${texts.filter((o) => o.nominal_u == null).length} without nominal_u, ` +
        `${texts.filter((o) => !o.color).length} without color -> contrast unchecked), ${fails.length} fail / ${warns.length} warn` +
        (warns.length ? ` [${warns.map((w) => `${w.rule}@${w.t}`).join(', ')}]` : ''));
    }
  } catch (e) {
    bad.push(`real leg: ${String(e.message || e).split('\n').slice(0, 4).join(' | ')}`);
  } finally {
    rmSync(join(FILMS, KEY), { recursive: true, force: true });
  }

  return { pass: bad.length === 0, measured: bad.length ? bad.join('; ') : facts.join('; ') };
};
