// typeset (P2): the 40-formula battery through the REAL Eq (converter + MathTypst + labels),
// determinism, named parts, Persian RTL, and a broken formula's loud error. Everything runs in
// ONE capped python process (the battery is a batch, not 40 scenes).
import { homedir } from 'node:os';
import { join } from 'node:path';
import { writeFileSync } from 'node:fs';
import { CAPS, TIMEOUTS, MemPool, runCapped } from '../../lib/capped.mjs';
import { pythonFor } from '../../doctor.mjs';
import { ROOT } from '../../lib/serve.mjs';

const BATTERY = [
  // (name, LaTeX) — the S2 battery, now through Eq: fractions, radicals, matrices, cases, aligned,
  // big operators, integrals, vectors, \text, colored parts, Greek, primes, binomials, sets…
  // (JS strings: LaTeX backslashes are doubled in normal string literals)
  ["frac", "x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}"],
  ["simple", "a^2 + b^2 = c^2"],
  ["sum", "\\sum_{k=1}^{n} k = \\frac{n(n+1)}{2}"],
  ["integral", "\\int_0^1 x^2 \\, dx = \\frac{1}{3}"],
  ["det2", "\\det\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix} = ad - bc"],
  ["matrix3", "\\begin{pmatrix} 2 & 1 & 0 \\\\ 1 & 3 & 1 \\\\ 0 & 1 & 2 \\end{pmatrix}"],
  ["cases", "|x| = \\begin{cases} x & x \\ge 0 \\\\ -x & x < 0 \\end{cases}"],
  ["aligned", "\\begin{aligned} (x+1)^2 &= x^2 + 2x + 1 \\\\ &= x^2 + 2x + 1 \\end{aligned}"],
  ["lim", "\\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}"],
  ["trig", "\\sin^2\\theta + \\cos^2\\theta = 1"],
  ["euler", "e^{i\\pi} + 1 = 0"],
  ["vector", "\\vec{v} = \\begin{pmatrix} 3 \\\\ 1 \\end{pmatrix}"],
  ["abs", "|A| = 5"],
  ["text", "\\text{area} \\times 5"],
  ["big_op", "\\prod_{i=1}^{n} i = n!"],
  ["sqrt", "\\sqrt{2} \\approx 1.414"],
  ["ineq", "a < b \\le c"],
  ["det_area", "|\\det A| \\cdot \\text{area}(\\square)"],
  ["greek", "\\alpha\\beta\\gamma\\delta\\epsilon"],
  ["prime", "f'(x) = 2x"],
  ["double", "f''(x) = 2"],
  ["sub", "a_1 + a_2 + a_3"],
  ["binom", "\\binom{n}{k} = \\frac{n!}{k!(n-k)!}"],
  ["norm", "\\|\\vec{v}\\| = \\sqrt{v_1^2 + v_2^2}"],
  ["partial", "\\frac{\\partial f}{\\partial x}"],
  ["set", "x \\in \\mathbb{R}"],
  ["forall", "\\forall \\epsilon > 0\\ \\exists \\delta > 0"],
  ["hat", "\\hat{y} = mx + b"],
  ["bar", "\\bar{x} = \\frac{1}{n}\\sum_{i=1}^n x_i"],
  ["arrow", "x \\mapsto f(x)"],
  ["long_eq", "\\det(A - \\lambda I) = 0"],
  ["piecewise", "f(x) = \\begin{cases} 0 & x < 0 \\\\ 1 & x \\ge 0 \\end{cases}"],
  ["sum_prod", "\\sum_{i=1}^{n} a_i \\prod_{j \\ne i} \\frac{x - x_j}{x_i - x_j}"],
  ["exp_series", "e^x = \\sum_{k=0}^{\\infty} \\frac{x^k}{k!}"],
  ["norm2", "\\|A\\vec{x}\\| \\le \\|A\\| \\|\\vec{x}\\|"],
  ["inverse", "A^{-1} = \\frac{1}{ad-bc}\\begin{pmatrix} d & -b \\\\ -c & a \\end{pmatrix}"],
  ["eigen", "A\\vec{v} = \\lambda\\vec{v}"],
  ["deriv_def", "\\frac{d}{dx}\\left[ x^n \\right] = n x^{n-1}"],
  ["big_o", "\\text{err} = O(h^2)"],
  ["mod", "a \\equiv b \\pmod{n}"],
];

export default async () => {
  const pool = new MemPool();
  const py = pythonFor('manim');
  const prog = join(ROOT, 'engine', 'manim', 'test', 'typeset-battery.py');
  writeFileSync(prog, `# generated by the typeset check — the battery as JSON on stdin
import hashlib, json, sys, warnings
warnings.filterwarnings("ignore")
sys.path.insert(0, ${JSON.stringify(join(ROOT, 'engine', 'manim'))})
from studio_manim import Eq, Txt
battery = json.load(sys.stdin)
rows, fail = [], []
for name, tex in battery["items"]:
    try:
        m = Eq(tex)
        rows.append((name, m.width, m.height, len(m.submobjects)))
    except Exception as e:
        fail.append((name, str(e).splitlines()[0][:120] if str(e) else repr(e)))
print(json.dumps({"ok": [r[0] for r in rows], "n": len(rows), "fail": fail}))
# determinism: the same 10 formulas again -> identical geometry
h1 = [hashlib.sha256(str(Eq(battery["items"][i][1]).points).encode()).hexdigest()[:12] for i in range(0, 40, 4)]
h2 = [hashlib.sha256(str(Eq(battery["items"][i][1]).points).encode()).hexdigest()[:12] for i in range(0, 40, 4)]
print(json.dumps({"deterministic": h1 == h2, "hashes": h1[:3]}))
# named parts select and color
e = Eq("{{ad}} - {{bc}} = 5")
try:
    p1 = e.part("p1"); p1.set_color("#A86400")
    parts_ok = p1 is not None and len(e.labels) == 2
except Exception as ex:
    parts_ok = str(ex)
print(json.dumps({"parts": parts_ok}))
# a Persian sentence through Txt shapes RTL and every codepoint is in the font (Pango handles it)
try:
    fa = Txt("مساحت زیر منحنی پنج برابر می‌شود", role="body")
    print(json.dumps({"persian": True, "width": round(float(fa.width), 2)}))
except Exception as ex:
    print(json.dumps({"persian": False, "err": str(ex)[:120]}))
`);
  const r = await pool.run({
    cmd: py, args: [prog], cwd: join(homedir(), '.cache', 'pi-motion-studio', 'scratch'),
    // ^ cwd in SCRATCH (Manim writes media/ into its cwd: engine/manim was the original leak,
    // engine/manim/test was the second — a Pango cache belongs under ~/.cache, never the repo)
    input: JSON.stringify({ items: BATTERY }), memoryMb: CAPS.check, timeoutS: TIMEOUTS.check * 2,
    label: 'typeset battery',
    env: { STUDIO_FORMAT: '16:9' },
  });
  if (r.killed) return { pass: false, measured: `battery killed (${r.reason}) — memory/time` };
  const out = (r.out || '').trim().split('\n').filter((l) => l.startsWith('{')).map((l) => JSON.parse(l));
  const [batch, det, parts, persian] = out;
  const bad = [];
  if (!batch) return { pass: false, measured: `battery produced no result:\n${(r.out + r.err).slice(-300)}` };
  if (batch.fail.length) bad.push(`${batch.fail.length} formulas failed: ${batch.fail.map((f) => `${f[0]}(${f[1].slice(0, 40)})`).join(', ')}`);
  if (batch.n !== BATTERY.length) bad.push(`only ${batch.n}/${BATTERY.length} compiled`);
  if (!det?.deterministic) bad.push('repeated formulas differ (determinism)');
  if (parts?.parts !== true) bad.push(`named parts broken: ${parts?.parts}`);
  if (persian?.persian !== true) bad.push(`Persian RTL failed: ${persian?.err}`);
  // the deliberately broken formula fails LOUD with the formula in the message
  const broken = await pool.run({
    cmd: py, args: ['-c', 'import sys; sys.path.insert(0, ' + JSON.stringify(join(ROOT, 'engine', 'manim')) +
      ')\nimport warnings; warnings.filterwarnings("ignore")\nfrom studio_manim import Eq\ntry:\n    Eq(r"\\\\this \\{is not} a formula")\n    print("BAD: broken formula compiled")\nexcept Exception as e:\n    print("LOUD:", str(e).splitlines()[0][:100])'],
    memoryMb: CAPS.check, timeoutS: 120, label: 'typeset broken-formula',
    env: { STUDIO_FORMAT: '16:9' },
  });
  if (!/LOUD:/.test(broken.out) || /BAD:/.test(broken.out)) bad.push(`a broken formula did not fail loudly: ${(broken.out || broken.err || '').trim().split('\n')[0]}`);

  const measured = `${batch.n}/${BATTERY.length} compile (${(batch.fail || []).length} fail), deterministic=${det?.deterministic}, parts=${parts?.parts}, persian=${persian?.persian}, broken-formula loud`;
  return { pass: bad.length === 0, measured: bad.length ? bad.join('; ') : measured };
};
