// Deterministic test media for the editing pipeline, generated by ffmpeg (and the engine itself) into
// ~/.cache/pi-motion-studio/fixtures: outside git, built once, checksummed in manifest.json, offline afterwards.
//   studio fixtures [--list] [--only a,b] [--force] [--verify]
import { createHash } from 'node:crypto';
import { createReadStream, existsSync, mkdirSync, readFileSync, rmSync, statSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { BARCODE, barcodeSource } from './lib/barcode.mjs';
import { readJson, writeJson } from './lib/film.mjs';
import { synthMusic, writeWav } from './audio.mjs';
import { pythonFor } from './doctor.mjs';
import { ROOT } from './lib/serve.mjs';
import { run } from './lib/proc.mjs';
import { writeFileSync } from 'node:fs';

export const FIXTURE_DIR = join(homedir(), '.cache', 'pi-motion-studio', 'fixtures');
const MANIFEST = join(FIXTURE_DIR, 'manifest.json');
const RECIPE = 1; // bump to invalidate every fixture when a recipe changes

const BEEP = (dur, rate, period = 2) => `aevalsrc=exprs='0.7*sin(2*PI*1000*t)*lt(mod(t,${period}),0.05)':s=${rate}:d=${dur}`;
const ENC = ['-fflags', '+bitexact', '-flags:v', '+bitexact', '-flags:a', '+bitexact'];
const x264 = (crf = 18, extra = []) => ['-c:v', 'libx264', '-preset', 'medium', '-crf', String(crf), '-pix_fmt', 'yuv420p', '-threads', '4', ...extra];
const ff = (args) => run('ffmpeg', ['-y', '-v', 'error', '-nostdin', ...args]);

// 1280x720 base: testsrc2 + barcode (+ a full-frame white flash on the frame at every 2 s)
const sync = ({ w = 1280, h = 720, fps = 30, dur = 30, flashEvery = 2 }) => ({
  v: [`-f`, 'lavfi', '-i', `testsrc2=s=${w}x${h}:r=${fps}:d=${dur}`, '-f', 'lavfi', '-i', barcodeSource(fps, dur)],
  fc: `[0:v][1:v]overlay=0:0,drawbox=x=0:y=${BARCODE.cell}:w=iw:h=ih-${BARCODE.cell}:color=white:t=fill:enable='eq(mod(n,${fps * flashEvery}),0)',format=yuv420p[v]`,
});


// ── speech fixtures: Piper TTS (public-domain / CC voices) with a known script ──────────────────────
const VOICES = join(homedir(), '.local', 'share', 'pi-motion-studio', 'models', 'piper');
const voice = (name) => join(VOICES, `${name}.onnx`);
const EN_SCRIPT = [
  { say: 'Welcome to the studio.' }, { pause: 0.9 },
  { say: 'um', kind: 'filler', length: 1.6 }, { pause: 0.3 },
  { say: 'Today I want to talk about how we edit video.' }, { pause: 0.6 },
  { say: 'The first rule is simple. Fix the sound before the picture.' }, { pause: 1.4 },
  { say: 'The second rule is cut on the breath, not in the', kind: 'flub' }, { pause: 0.5 },
  { say: 'uh', kind: 'filler', length: 1.6 }, { pause: 0.25 },
  { say: 'The second rule is to cut on the breath, never in the middle of a word.' }, { pause: 0.8 },
  { say: 'Third, keep the captions big and readable on a phone.' }, { pause: 0.5 },
  { say: 'um', kind: 'filler', length: 1.6 }, { pause: 0.3 },
  { say: 'That is all it takes to make an edit feel professional.' }, { pause: 0.4 },
];
const FA_SCRIPT = [
  { say: 'سلام، به استودیو خوش آمدید.' }, { pause: 0.8 },
  { say: 'امروز می‌خواهم درباره ویرایش ویدیو صحبت کنم.' }, { pause: 0.7 },
  { say: 'قانون اول ساده است: صدا را قبل از تصویر درست کنید.' }, { pause: 0.9 },
  { say: 'زیرنویس‌ها باید بزرگ و روی تلفن خوانا باشند.' }, { pause: 0.4 },
];
const PODCAST_SCRIPT = [
  ['a', 'Welcome back to the show. Today we are talking about editing video from the command line.'], ['b', 'Thanks for having me. I think the biggest surprise is how much of editing is just listening.'],
  ['a', 'Say more about that.'], ['b', 'Well, you cut on the breath. If you cut in the middle of a word, the viewer feels it even if they cannot say why.'],
  ['a', 'And what about captions?'], ['b', 'Captions are design. Big, readable, one accent color, and never over the speaker face.'],
  ['a', 'That makes sense. Where can people see your work?'], ['b', 'Everything is on the studio page. Thanks again.'],
].flatMap(([v, t], i) => [{ say: t, voice: v }, { pause: i % 2 ? 0.7 : 0.4 }]);

async function speechAudio(dir, id, { script, voices, noise = '', roomtone = -58 }) {
  const spec = join(dir, `.${id}.spec.json`), wav = join(dir, `${id}.wav`), truth = join(dir, `${id}.truth.json`);
  writeFileSync(spec, JSON.stringify({ voices, items: script, roomtone_db: roomtone }));
  await run(pythonFor('ml'), [join(new URL('.', import.meta.url).pathname, 'speechgen.py'), '--spec', spec, '--out', wav + '.22k.wav', '--truth', truth, '--noise', noise]);
  await ff(['-i', wav + '.22k.wav', '-ar', '48000', '-ac', '1', '-c:a', 'pcm_s16le', ...ENC, wav]);
  rmSync(wav + '.22k.wav', { force: true }); rmSync(spec, { force: true });
  return { wav, truth, duration: JSON.parse(readFileSync(truth, 'utf8')).duration };
}

export const FIXTURES = {
  // frame-index barcode, flash + 1 kHz beep every 2 s; long GOP + B-frames on purpose (conform must fix that)
  sync: { file: 'sync.mp4', desc: '30 s 1280x720 30 fps, barcode, flash+beep every 2 s, 48 kHz stereo, long GOP', async build(out) {
    const s = sync({});
    await ff([...s.v, '-f', 'lavfi', '-i', BEEP(30, 48000), '-filter_complex', s.fc, '-filter_complex_threads', '1', '-map', '[v]', '-map', '2:a', ...x264(18, ['-g', '250', '-bf', '2']), '-c:a', 'aac', '-b:a', '128k', '-ac', '2', ...ENC, out]);
  } },
  // portrait phone clip: stored landscape + rotation tag, variable frame rate, 44.1 kHz. Display is 720x1280 upright, barcode top-left.
  'vfr-rotated': { file: 'vfr-rotated.mp4', desc: '20 s portrait phone clip: rotation tag, VFR (every 5th frame dropped, never a flash frame), 44.1 kHz', async build(out, dir) {
    const s = sync({ w: 720, h: 1280, dur: 20 }), tmp = join(dir, '.vfr-src.mp4');
    // 1) upright portrait content, VFR via a deterministic drop; 2) store it rotated and tag the rotation
    await ff([...s.v, '-f', 'lavfi', '-i', BEEP(20, 44100), '-filter_complex', `${s.fc.replace('[v]', '')},select='not(eq(mod(n,5),3))',transpose=2[v]`, '-map', '[v]', '-map', '2:a', ...x264(18), '-fps_mode', 'vfr', '-c:a', 'aac', '-b:a', '96k', ...ENC, tmp]);
    await ff(['-display_rotation:v:0', '-90', '-i', tmp, '-c', 'copy', ...ENC, out]);
    rmSync(tmp, { force: true });
  } },
  // 10-bit HLG: genuinely HLG-encoded pixels, bt2020 tags
  hlg: { file: 'hlg.mp4', desc: '6 s 1280x720 25 fps 10-bit HLG (bt2020, arib-std-b67), HEVC', async build(out) {
    const s = sync({ fps: 25, dur: 6 });
    await ff([...s.v, '-filter_complex', `${s.fc.replace('[v]', '')},zscale=pin=709:tin=709:min=709:rin=tv:p=2020:t=arib-std-b67:m=2020_ncl:r=tv,format=yuv420p10le[v]`, '-map', '[v]',
      '-c:v', 'libx265', '-preset', 'fast', '-crf', '18', '-x265-params', 'log-level=error:colorprim=bt2020:transfer=arib-std-b67:colormatrix=bt2020nc:range=limited', '-colorspace', 'bt2020nc', '-color_primaries', 'bt2020', '-color_trc', 'arib-std-b67', '-color_range', 'tv', '-tag:v', 'hvc1', ...ENC, out]);
  } },
  noaudio: { file: 'noaudio.mp4', desc: '8 s 1280x720 30 fps with a barcode and no audio stream', async build(out) {
    const s = sync({ dur: 8 });
    await ff([...s.v, '-filter_complex', s.fc, '-map', '[v]', ...x264(20), '-an', ...ENC, out]);
  } },
  // 20 minutes of 1080p30 for A/V drift, ingest speed and memory budgets (barcode 16 bits covers 36000 frames)
  long: { file: 'long.mp4', desc: '20 min 1920x1080 30 fps, barcode, flash+beep every 2 s', slow: true, async build(out) {
    const s = sync({ w: 1920, h: 1080, dur: 1200 });
    await ff([...s.v, '-f', 'lavfi', '-i', BEEP(1200, 48000), '-filter_complex', s.fc, '-map', '[v]', '-map', '2:a', ...x264(30, ['-preset', 'veryfast', '-g', '250']), '-c:a', 'aac', '-b:a', '96k', '-ac', '2', ...ENC, out]);
  } },
  // a bright disc on a textured background; centre = (640 + 400 sin(2πt/10), 360 + 150 sin(2πt/6.7))
  subject: { file: 'subject.mp4', desc: '20 s 1280x720 30 fps, a moving disc whose centre follows a known path', truth: { cx: '640+400*sin(2*pi*t/10)', cy: '360+150*sin(2*pi*t/6.7)', r: 60 }, async build(out) {
    await ff(['-f', 'lavfi', '-i', 'color=c=0x2a3340:s=1280x720:r=30:d=20,noise=alls=14:allf=u:all_seed=7',
      '-f', 'lavfi', '-i', `color=c=black:s=120x120:r=30:d=20,format=rgba,geq=r=255:g=90:b=40:a='if(lt(hypot(X-60,Y-60),58),255,0)'`,
      '-filter_complex', `[0:v][1:v]overlay=x='640+400*sin(2*PI*t/10)-60':y='360+150*sin(2*PI*t/6.7)-60':eval=frame,format=yuv420p[v]`, '-map', '[v]', ...x264(22), '-an', ...ENC, out]);
  } },

  // TTS speech with ums, pauses, one flubbed sentence (retaken right after) and a known script; picture = barcode clip
  speech: { file: 'speech.mp4', extra: ['speech.wav', 'speech.truth.json'], desc: 'TTS speech (ljspeech, public domain): 3 fillers, pauses 0.25-1.4 s, one flubbed sentence then its retake; + barcode video', needs: 'ml',
    async build(out, dir) {
      const { wav, duration } = await speechAudio(dir, 'speech', { script: EN_SCRIPT, voices: { a: voice('en_US-ljspeech-medium') } });
      const s = sync({ dur: Math.ceil(duration * 30) / 30 });
      await ff([...s.v, '-i', wav, '-filter_complex', s.fc, '-map', '[v]', '-map', '2:a', ...x264(20), '-c:a', 'aac', '-b:a', '128k', '-ac', '2', '-shortest', ...ENC, out]);
    } },
  'speech-fa': { file: 'speech-fa.wav', extra: ['speech-fa.truth.json'], desc: 'Persian TTS (amir, CC0): 4 sentences, for language auto-detect and RTL', needs: 'ml',
    async build(out, dir) { await speechAudio(dir, 'speech-fa', { script: FA_SCRIPT, voices: { a: voice('fa_IR-amir-medium') } }); } },
  noisy: { file: 'noisy.wav', extra: ['noisy.truth.json'], desc: 'the speech script with -32 dB hiss and 50 Hz hum (+harmonics) added', needs: 'ml',
    async build(out, dir) { await speechAudio(dir, 'noisy', { script: EN_SCRIPT, voices: { a: voice('en_US-ljspeech-medium') }, noise: 'hiss+hum' }); } },
  'podcast': { file: 'podcast.m4a', extra: ['podcast.truth.json'], desc: 'two-voice conversation (ljspeech + northern_english_male CC-BY-SA), audio only', needs: 'ml',
    async build(out, dir) {
      const { wav } = await speechAudio(dir, 'podcast', { script: PODCAST_SCRIPT, voices: { a: voice('en_US-ljspeech-medium'), b: voice('en_GB-northern_english_male-medium') } });
      await ff(['-i', wav, '-c:a', 'aac', '-b:a', '128k', ...ENC, out]); rmSync(wav, { force: true });
    } },
  // A real open-licensed talking head (NASA, public domain): fetched once, pinned by sha256, offline afterwards.
  'real-talking-head': { file: 'real/talking-head-original.webm', desc: 'REAL footage: NASA Johnson, 54 s 720p 30000/1001 VP8+Vorbis, public domain (see docs/editing/THIRD_PARTY.md)', sha256: 'f3dd2f87b8dedbc6ea9864af594e2de4fc8a2b5d425f85f834ba7f36c1d04472',
    async build(out) {
      mkdirSync(join(FIXTURE_DIR, 'real'), { recursive: true });
      const r = await fetch('https://upload.wikimedia.org/wikipedia/commons/c/ce/Astronaut_Scott_Kelly_Speaks_Out_Against_Bullying.webm', { headers: { 'user-agent': 'pi-motion-studio-fixtures/1.0 (private test fixture)' } });
      if (!r.ok) throw new Error(`download failed: HTTP ${r.status}`);
      writeFileSync(out, Buffer.from(await r.arrayBuffer()));
      if ((await sha256(out)) !== FIXTURES['real-talking-head'].sha256) { rmSync(out, { force: true }); throw new Error('real-talking-head: sha256 mismatch after download'); }
    } },
  // a track with a steady beat from the engine's own synth; the beat grid is exact truth (120 bpm: 0.5 s)
  song: { file: 'song.wav', extra: ['song.truth.json'], desc: '40 s steady 120 bpm A-minor track (engine synth), beat grid in song.truth.json', async build(out, dir) {
    const bus = synthMusic({ bpm: 120, key: 'A minor', style: 'drive', seed: 11 }, 40, false);
    writeWav(out, bus.L, bus.R);
    writeFileSync(join(dir, 'song.truth.json'), JSON.stringify({ bpm: 120, duration: 40, beats: Array.from({ length: 80 }, (_, i) => i * 0.5) }));
  } },
  // 12 short distinct clips for montages: colour by index, big number, a moving block, a per-clip pitch, barcode = frame in clip
  clips12: { file: 'clips12/clip01.mp4', extra: Array.from({ length: 11 }, (_, i) => `clips12/clip${String(i + 2).padStart(2, '0')}.mp4`).concat('clips12/clips.json'), desc: '12 clips, 2.0-3.5 s each, 1280x720 30 fps with audio, numbered 01-12', async build(out, dir) {
    mkdirSync(join(dir, 'clips12'), { recursive: true });
    const font = join(ROOT, 'engine', 'fonts', 'Inter.ttf'), list = [];
    for (let i = 0; i < 12; i++) {
      const dur = 2 + (i % 4) * 0.5, hue = (i * 30) % 360, f = join(dir, 'clips12', `clip${String(i + 1).padStart(2, '0')}.mp4`);
      const hex = hslHex(hue, 0.55, 0.32);
      await ff(['-f', 'lavfi', '-i', `color=c=${hex}:s=1280x720:r=30:d=${dur}`, '-f', 'lavfi', '-i', barcodeSource(30, dur), '-f', 'lavfi', '-i', `sine=f=${220 * 2 ** (i / 12)}:r=48000:d=${dur}`,
        '-filter_complex', `[0:v][1:v]overlay=0:0,drawtext=fontfile=${font}:text='${String(i + 1).padStart(2, '0')}':fontsize=300:fontcolor=white:x=(w-text_w)/2:y=(h-text_h)/2,drawbox=x='100+900*t/${dur}':y=620:w=80:h=40:color=white:t=fill,format=yuv420p[v]`,
        '-map', '[v]', '-map', '2:a', ...x264(20), '-c:a', 'aac', '-b:a', '96k', '-ac', '2', '-af', 'volume=0.3', '-shortest', ...ENC, f]);
      list.push({ file: `clip${String(i + 1).padStart(2, '0')}.mp4`, duration: dur, hue });
    }
    writeFileSync(join(dir, 'clips12', 'clips.json'), JSON.stringify(list, null, 1));
  } },
  // synthetic screen recording: typing bursts, a progress animation, long idle stretches (truth below). Idle = pixel-identical frames.
  screen: { file: 'screen.mp4', extra: ['screen.truth.json'], desc: '30 s 1280x720 30 fps: typing 1-3.9 s and 10-13 s, progress bar 17-20.8 s, everything else pixel-identical; beep every 2 s (freezedetect n=-75dB)',
    truth: { active: [[1, 3.9], [10, 13], [17, 20.8]], idle: [[0, 1], [3.9, 10], [13, 17], [20.8, 30]] },
    async build(out, dir) {
      const font = join(ROOT, 'engine', 'fonts', 'JetBrainsMono.ttf'), adv = 36, x0 = 40;
      const lines = [{ y: 110, text: '$ studio render launch --draft', t0: 1.0, rate: 10 }, { y: 210, text: '$ studio gate launch > gate.log', t0: 10.0, rate: 10 }];
      let g = `color=c=0x1e1f22:s=1280x720:r=30:d=30,drawbox=x=0:y=0:w=iw:h=48:color=0x2b2d31:t=fill,drawbox=x=24:y=18:w=14:h=14:color=0xff5f57:t=fill,drawbox=x=48:y=18:w=14:h=14:color=0xfebc2e:t=fill,drawbox=x=72:y=18:w=14:h=14:color=0x28c840:t=fill,drawbox=x=80:y=420:w=1120:h=160:color=0x3a3d44:t=fill`;
      for (const l of lines) [...l.text].forEach((ch, k) => { if (ch === ' ') return; g += `,drawtext=fontfile=${font}:text='${ch}':fontsize=60:fontcolor=0xd7dae0:x=${x0 + k * adv}:y=${l.y}:enable='gte(t,${(l.t0 + k / l.rate).toFixed(3)})'`; });
      // drawbox evaluates w once at init (no per-frame t), so the bar grows in 20 fixed steps, one every 0.2 s
      for (let k = 0; k < 20; k++) g += `,drawbox=x=${80 + 56 * k}:y=420:w=56:h=160:color=0x4ea1ff:t=fill:enable='gte(t,${(17 + 0.2 * k).toFixed(1)})'`;
      g += ',format=yuv420p[v]';
      const script = join(dir, '.screen.filter'); writeFileSync(script, g);
      await ff(['-f', 'lavfi', '-i', 'color=c=black:s=16x16:r=30:d=30', '-f', 'lavfi', '-i', BEEP(30, 48000), '-filter_complex_script', script, '-map', '[v]', '-map', '1:a', ...x264(20), '-c:a', 'aac', '-b:a', '96k', '-ac', '2', ...ENC, out]);
      rmSync(script, { force: true });
      writeFileSync(join(dir, 'screen.truth.json'), JSON.stringify(FIXTURES.screen.truth));
    } },
};

// hsl -> #rrggbb for ffmpeg colour sources
const hslHex = (h, sat, l) => { const a = sat * Math.min(l, 1 - l), f = (n) => { const k = (n + h / 30) % 12; return Math.round(255 * (l - a * Math.max(-1, Math.min(k - 3, 9 - k, 1)))); }; return '0x' + [f(0), f(8), f(4)].map((x) => x.toString(16).padStart(2, '0')).join(''); };

const sha256 = (file) => new Promise((ok, bad) => { const h = createHash('sha256'); createReadStream(file).on('data', (d) => h.update(d)).on('end', () => ok(h.digest('hex'))).on('error', bad); });

export const fixturePath = (id) => { const f = FIXTURES[id]; if (!f) throw new Error(`unknown fixture "${id}"`); return join(FIXTURE_DIR, f.file); };

// Build what is missing (or everything with force). Returns the manifest entries touched.
export async function ensureFixtures({ only, force = false, verify = false, includeSlow = true, log = console.log } = {}) {
  mkdirSync(FIXTURE_DIR, { recursive: true });
  const manifest = readJson(MANIFEST, { recipe: RECIPE, fixtures: {} });
  if (manifest.recipe !== RECIPE) { manifest.recipe = RECIPE; manifest.fixtures = {}; force = true; }
  const ids = (only ? only : Object.keys(FIXTURES)).filter((id) => FIXTURES[id] && (includeSlow || !FIXTURES[id].slow));
  const touched = {};
  for (const id of ids) {
    const f = FIXTURES[id], out = join(FIXTURE_DIR, f.file), have = manifest.fixtures[id];
    const extras = f.extra || [];
    const ok = !force && have && existsSync(out) && extras.every((x) => existsSync(join(FIXTURE_DIR, x))) && statSync(out).size === have.bytes && (!verify || (await sha256(out)) === have.sha256);
    if (ok) { touched[id] = { ...have, cached: true }; continue; }
    const t0 = Date.now();
    if (existsSync(out)) rmSync(out, { force: true });
    log(`fixture ${id}: building (${f.desc})`);
    await f.build(out, FIXTURE_DIR);
    manifest.fixtures[id] = { file: f.file, ...(f.extra ? { extra: f.extra } : {}), bytes: statSync(out).size, sha256: await sha256(out), desc: f.desc, ...(f.truth ? { truth: f.truth } : {}), built_at: new Date().toISOString(), seconds: +((Date.now() - t0) / 1000).toFixed(1) };
    touched[id] = manifest.fixtures[id];
    writeJson(MANIFEST, manifest);
  }
  writeJson(MANIFEST, manifest);
  return touched;
}

export const readManifest = () => readJson(MANIFEST, { recipe: RECIPE, fixtures: {} });
