# generated by the typeset check — the battery as JSON on stdin
import hashlib, json, sys, warnings
warnings.filterwarnings("ignore")
sys.path.insert(0, "/mnt/c/Users/Hp/Desktop/pi-motion-studio/engine/manim")
from studio_manim import Eq, Txt
battery = json.load(sys.stdin)
rows, fail = [], []
for name, tex in battery["items"]:
    try:
        m = Eq(tex)
        rows.append((name, m.width, m.height, len(m.submobjects)))
    except Exception as e:
        fail.append((name, str(e).splitlines()[0][:120] if str(e) else repr(e)))
print(json.dumps({"ok": [r[0] for r in rows], "n": len(rows), "fail": fail}))
# determinism: the same 10 formulas again -> identical geometry
h1 = [hashlib.sha256(str(Eq(battery["items"][i][1]).points).encode()).hexdigest()[:12] for i in range(0, 40, 4)]
h2 = [hashlib.sha256(str(Eq(battery["items"][i][1]).points).encode()).hexdigest()[:12] for i in range(0, 40, 4)]
print(json.dumps({"deterministic": h1 == h2, "hashes": h1[:3]}))
# named parts select and color
e = Eq("{{ad}} - {{bc}} = 5")
try:
    p1 = e.part("p1"); p1.set_color("#A86400")
    parts_ok = p1 is not None and len(e.labels) == 2
except Exception as ex:
    parts_ok = str(ex)
print(json.dumps({"parts": parts_ok}))
# a Persian sentence through Txt shapes RTL and every codepoint is in the font (Pango handles it)
try:
    fa = Txt("مساحت زیر منحنی پنج برابر می‌شود", role="body")
    print(json.dumps({"persian": True, "width": round(float(fa.width), 2)}))
except Exception as ex:
    print(json.dumps({"persian": False, "err": str(ex)[:120]}))
